### ISSUE TITLE
The knowledge distillation code

### ISSUE THREAD

**Issue by Christina0717** [yegcjs/DINOISER#2]
Hi, thanks for the great work. I wonder if you can release the knowledge distillation code, which can be helpful to reproduct the results of the paper. Thanks a lot.

**Comment by yegcjs** [comment]
Thanks for your interest! We directly use knowledge distillation data from https://github.com/shawnkx/Fully-NAT. You can download or reproduce the data from theie repository.

**Comment by Christina0717** [comment]
Thanks for your reply. It has assisted me in resolving the issue.
